
---
- hosts: localhost
  tasks:
    - name: Install software
      become: yes
      become_user: root
      apt:  name={{item}} state=installed 
      with_items:
        - geany
        - vim-gtk3
        - mesa-common-dev
        - qbs
        - git
        - libvte-dev
        - build-essential
        - dkms
    - name: Config git
      shell: |
         git config --global user.name "Ben Lau"
         git config --global user.email "xbenlau@gmail.com"
    - name: Qt Online installer
      get_url:
        url: https://download.qt.io/archive/online_installers/3.0/qt-unified-linux-x64-3.0.4-online.run
        dest: /home/benlau/Downloads
        mode: u+rwx
    - name: Ansible PPA
      become: yes
      become_user: root
      apt_repository:
        repo: ppa:ansible/ansible
        state: present
    - name: vboxsf group checking
      shell: "grep -q vboxsf /etc/group"
      register: vboxsf_exists
      ignore_errors: true
    - debug:  msg="vboxsf_exists {{vboxsf_exists.rc}}"
    - name: Append vboxsf group
      become: yes
      become_user: root
      user:
        name: benlau
        groups: vboxsf
        append: yes
      when: vboxsf_exists.rc == 0
