
---
- hosts: localhost
  tasks:
    - name: Install software
      become: yes
      become_user: root
      apt:  name={{item}} state=installed 
      with_items:
        - geany
        - vim-gtk3
        - mesa-common-dev
        - qbs
        - git
        - libvte-dev
        - build-essential
    - name: Config git
      shell: |
         git config --global user.name "Ben Lau"
         git config --global user.email "xbenlau@gmail.com"
    - name: User Group
      user:
        name: benlau
        groups: vboxsf
        append: yes
    - name: Config
      dconf:
        key: "/org/gnome/desktop/lockdown/disable-lock-screen"
        value: "true"         
        state: present
