name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Cache emsdk
      uses: actions/cache@v3
      with:
        path: emsdk
        key: emsdk
    - name: Install emsdk
      run: |
        which node
        node --version
        if [ ! -d "emsdk" ]; then
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk activate latest
          ./emsdk install latest
        fi
        find emsdk        
